spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://ec2-3-237-55-151.compute-1.amazonaws.com:5432/d60h1vp1l61o37
    username: mehajlyypuecgd
    password: 06eadb823a52b950c0b55568b4b071a26bd71c902cd0317b79de51f5c778246d

server:
  port: ${PORT:80}