spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://ec2-18-214-238-28.compute-1.amazonaws.com:5432/d412sora5ha26g
    username: qpqeyttubkmdoy
    password: 457f711f262c2404d440abc60db29607417fca92780d14bba68208b3e42ffffd

server:
  port: ${PORT:80}