spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://dpg-cka3adldrqvc73at6mpg-a.oregon-postgres.render.com:5432/developmentdb_rsm5
    username: abnerlucas
    password: ZCd7HiL6KQrSQklr3e35NerzGNxb2u4a

server:
  port: 8080