spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

server:
  port: ${PORT:3000}